# .github/workflows/master_gamereviewer.yml

name: Build and deploy ASP.Net Core app to Azure Web App - GameReviewer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6169BD13E7524D339B58F91058185428 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_75A1710F50B04FECA2C8E67F6578987A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A08A445364164387B4EAC19AA8CC72E8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'GameReviewer'
          slot-name: 'Production'
          package: ./GameReviewer.DataAccess   # Path to your DataAccess project

      - name: Deploy frontend to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'GameReviewer'  # Azure Web App name
          slot-name: 'Production'   # (Optional) Slot name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Azure Web App publish profile
          package: ./Frontend/gamereviewerreact  # Path to your frontend project
